### PR TITLE
Change jsonData in _iterPost to setdefault

### PR DESCRIPTION
**Pull request by Brycicle777**
Update jsonData continuation key setting to setdefault in case continuation does not exist as a key already, fixing KeyError

Also sorry if noob, still learning. Finally back into python after a year and a half of bathing in SQL for a different position

### CODE REVIEW

**Comment by null-directory** [comment]
This will set the continuation on jsonData, but _only_ if it wasn't already there. So it won't update on subsequent iterations... I _think_.

The `setdefault` won't matter in the assignment, so I'm guessing it broke on `lastResults` instead.
Perhaps...?
```python
jsonData['continuation'] = self.lastResults.get('continuation', False)
```

**Comment by Brycicle777** [comment]
> This will set the continuation on jsonData, but _only_ if it wasn't already there. So it won't update on subsequent iterations... I _think_.
> 
> 
> 
> The `setdefault` won't matter in the assignment, so I'm guessing it broke on `lastResults` instead.
> 
> Perhaps...?
> 
> ```python
> 
> jsonData['continuation'] = self.lastResults.get('continuation', False)
> 
> ```

That's probably more correct. I did notice .get was used above but not on that line. I would test it myself, but I was at work and didn't have the time to figure out how to test a library for the first time lol

**Comment by Brycicle777** [comment]
You're correct, set default would work the first time to set continuation as a key in jsonData, but it would NOT update subsequent values. 

Maybe something like
if 'continuation' in jsonData: jsonData['continuation'] = results['continuation'] else set default

Sorry if bad formatting, on mobile

Maybe tomorrow I'll figure out how to test the change on my personal laptop. It'd be a good exercise

**Comment by Brycicle777** [comment]
Updated my change to not dumbly use setdefault since that will only set the value the first time (assuming the key isn't already there) and then only retrieve the value for that key on subsequent loops.

There's probably a more "python-ey" way to implement the change, but this seems to work well, at least from my rudimentary testing in a virtualenv

I will leave you to your own testing though (and advise you to do it, considering I'm still a beginner)

**Pull request closed without merging**
